# Модуль Numpy. Массивы

In [200]:
import numpy as np

arr = np.array([1, 5, 2, 9, 10])
arr
# array([ 1,  5,  2,  9, 10])

array([ 1,  5,  2,  9, 10])

In [201]:
print(type(arr))

<class 'numpy.ndarray'>


`nd` - n-мерный

`array` - массив

Выше вариант одномерного массива

Рассмотрим двумерный массив:

In [202]:
nd_arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
nd_arr
# array([[1, 2, 3],
#    [4, 5, 6],
#    [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Массив — это структура данных, в которой:

1. Элементы хранятся в указанном порядке.

2. Каждый элемент можно получить по индексу за одинаковое время.

3. Все элементы приведены к одному и тому же типу данных.

4. Максимальное число элементов и объём выделенной памяти заданы заранее.

<div class="alert alert-block alert-success">
<b>Размерностью массива</b> называют то число индексов, которое необходимо для однозначного получения элемента из массива.

Соответственно, чтобы найти элемент в массиве размерности 1 (строка из чисел) достаточно одного индекса.
В двумерном массиве (таблице из чисел) потребуется уже два индекса: номер строки и номер столбца.
Для трёхмерного массива (например, контейнеры на судне расположены по длине, ширине и высоте судна) потребуется уже три индекса.
Максимальная размерность массива программно не ограничена, но с добавлением каждой размерности в несколько раз увеличивается объём требуемой для его хранения памяти. Поэтому в какой-то момент места для массива большой размерности может не хватить, однако фактическая максимальная размерность зависит от возможностей компьютера
</div>

<div class="alert alert-block alert-success">
<b>Форма (структура) массива</b> — это информация о количестве размерностей массива и протяжённости массива по каждой из размерностей. Например, можно задать двумерный массив размера 3x5 — у этой таблицы две размерности: 3 строки и 5 столбцов.
</div>

<div class="alert alert-block alert-error">
	<ul>
		<li>
		В списке не гарантируется получение любого элемента по индексу за одинаковое время (обычно чем больше индекс, тем дольше занимает время получения элемента).
		</li>
		<li>
		Также с совокупностью элементов списка работать дольше, чем с элементами массива. На самом деле Python list является чем-то средним между классическим списком из теории структур данных и массивом, но по скорости он тоже проигрывает массивам.
		</li>
	</ul>
</div>


<div class="alert alert-block alert-success">
Зато к преимуществам списка можно отнести легко изменяющуюся длину, а также возможность хранения данных разных типов в одной структуре данных. С другой стороны, последнее может быть и недостатком: при работе с массивами одинаковых данных можно быть уверенным, что там не окажется «сюрпризов» в виде данных неподходящего типа.
</div>

Задать тип данных сразу при создании массива можно с помощью параметра dtype:

In [203]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

Теперь, если добавить в arr число больше 127 или меньше -128, оно потеряет исходное значение, как и при преобразовании к меньшему типу:

In [204]:
arr[2] = 2000
arr
# DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
# For the old behavior, usually:
#     np.array(value).astype(dtype)
# will give the desired result (the cast overflows).
#   arr[2] = 2000
# array([  1,   5, -48,   9,  10], dtype=int8)

/var/folders/d5/gnc48lls2z5cctzzc3g518wh0000gn/T/ipykernel_27157/971784471.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)
will give the desired result (the cast overflows).
  arr[2] = 2000


array([  1,   5, -48,   9,  10], dtype=int8)

Если добавить float в массив int, пропадёт десятичная часть:

In [205]:
arr[2] = 125.5
arr
# array([  1,   5, 125,   9,  10], dtype=int8)

array([  1,   5, 125,   9,  10], dtype=int8)

Строку, которую можно преобразовать в число, можно сразу положить в массив. Она будет приведена к нужному типу автоматически:

In [206]:
arr[2] = '12'
arr
# array([ 1,  5, 12,  9, 10], dtype=int8)

array([ 1,  5, 12,  9, 10], dtype=int8)

А вот при попытке положить в массив строку, которую нельзя преобразовать в число, возникнет ошибка:

In [207]:
# arr[2] = 'test'
# ValueError: invalid literal for int() with base 10: 'test'

Поменять тип данных во всём массиве можно с помощью тех же функций, которыми мы пользовались для преобразования типов отдельных переменных в предыдущем юните (например, np.int32 или np.float128):

In [208]:
arr = np.float64(arr)
arr
# array([ 1.,  5., 12.,  9., 10.], dtype=float128)

array([ 1.,  5., 12.,  9., 10.])

При преобразовании типов данных в массиве не забывайте о том, что часть чисел может потерять смысл, если менять тип данных с более ёмкого на менее ёмкий:

In [209]:
arr = np.array([12321, -1234, 3435, -214, 100], dtype=np.int32)
arr
# array([12321, -1234,  3435,  -214,   100], dtype=int32)
 
arr = np.uint8(arr)
arr
# array([ 33,  46, 107,  42, 100], dtype=uint8)

array([ 33,  46, 107,  42, 100], dtype=uint8)

## Свойства NumPy-массивов

In [210]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

1. Узнать размерность массива можно с помощью .ndim:

In [211]:
arr.ndim
# 1
nd_arr.ndim
# 2

2

2. Узнать общее число элементов в массиве можно с помощью .size:

In [212]:
arr.size
# 5
nd_arr.size
# 9

9

3. Форма или структура массива хранится в атрибуте .shape:

In [213]:
arr.shape
# (5,)
nd_arr.shape
# (3, 3)

(3, 3)

<div class="alert alert-block alert-warning">
Форма массива хранится в виде кортежа с числом элементов, равным размерности массива. Соответственно, для одномерного массива напечатан кортеж длины 1. Обратите внимание, что для двумерного массива вначале было напечатано число «строк», а затем число «столбцов». Это так только отчасти. На самом деле массив как бы состоит из внешних и внутренних массивов: вспомните, что мы передавали список, состоящий из трёх списков, длина каждого из которых равнялась трём. Форма массива определяется от длины внешнего массива (3) к внутреннему (3).
</div>

4. Наконец, узнать, сколько «весит» каждый элемент массива в байтах позволяет .itemsize:

In [214]:
arr.itemsize
# 1
nd_arr.itemsize
# 2

2

## Заполнение новых массивов

Создадим одномерный массив из пяти элементов:

In [215]:
zeros_1d = np.zeros(5)
zeros_1d
# array([0., 0., 0., 0., 0.])

array([0., 0., 0., 0., 0.])

Создадим трёхмерный массив с формой 5x4x3 и типом float32:

In [216]:
zeros_3d = np.zeros((5,4,3), dtype=np.float32)
print(zeros_3d.shape)
# (5, 4, 3)

(5, 4, 3)


Ещё одной удобной функцией для создания одномерных массивов является `arange`. Она аналогична встроенной функции range, но обладает рядом особенностей. Вот её сигнатура: `arange([start,] stop, [step,], dtype=None)`.

Аргументы `start` (по умолчанию 0), `step` (по умолчанию 1) и `dtype` (определяется автоматически) являются необязательными:
 - `start` (входит в диапазон возвращаемых значений) задаёт начальное число;
 - `stop` (не входит в диапазон возвращаемых значений, как и при использовании range) задаёт правую границу диапазона;
 - `step` задаёт шаг, с которым в массив добавляются новые значения.
В отличие от `range`, в функции `arange` все перечисленные параметры могут иметь тип `float`.

In [217]:
np.arange(5)
# array([0, 1, 2, 3, 4])

array([0, 1, 2, 3, 4])

Создадим массив от 2.5 до 5:

In [218]:
np.arange(2.5, 5)
# array([2.5, 3.5, 4.5])

array([2.5, 3.5, 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5:

In [219]:
np.arange(2.5, 5, 0.5)
# array([2.5, 3. , 3.5, 4. , 4.5])

array([2.5, 3. , 3.5, 4. , 4.5])

Создадим массив от 2.5 до 5 с шагом 0.5 и с типом float16:

In [220]:
np.arange(2.5, 5, 0.5, dtype=np.float16)
# array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

array([2.5, 3. , 3.5, 4. , 4.5], dtype=float16)

На самом деле операции с плавающей точкой не всегда бывают предсказуемыми из-за особенностей хранения таких чисел в памяти компьютера. Поэтому для работы с дробными параметрами start, stop и step лучше использовать функцию linspace (англ. linear space — линейное пространство). Она тоже возвращает одномерный массив из чисел, расположенных на равном удалении друг от друга между началом и концом диапазона, но обладает немного другим поведением и сигнатурой:

`np.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None)`

 - `start` и stop являются обязательными параметрами, задающими начало и конец возвращаемого диапазона;
 - `num` — параметр, задающий число элементов, которое должно оказаться в массиве (по умолчанию 50);
 - `endpoint` — включён или исключён конец диапазона (по умолчанию включён);
 - `retstep` (по умолчанию False) позволяет указать, возвращать ли использованный шаг между значениями, помимо самого массива;
 - `dtype` — уже хорошо знакомый нам параметр, задающий тип данных (если не задан, определяется автоматически).
 
Давайте потренируемся. Создадим массив из десяти чисел между 1 и 2:


In [221]:
arr = np.linspace(1, 2, 10)
arr
# array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
#        1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

array([1.        , 1.11111111, 1.22222222, 1.33333333, 1.44444444,
       1.55555556, 1.66666667, 1.77777778, 1.88888889, 2.        ])

Создадим массив из десяти чисел между 1 и 2, не включая 2:

In [222]:
arr = np.linspace(1, 2, 10, endpoint=False)
arr
# array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

Узнаем, какой шаг был использован для создания массива из десяти чисел между 1 и 2, где 2 включалось и не включалось:

In [223]:
arr, step = np.linspace(1, 2, 10, endpoint=True, retstep=True)
print(step)
# 0.1111111111111111

arr, step = np.linspace(1, 2, 10, endpoint=False, retstep=True)
print(step)
# 0.1

0.1111111111111111
0.1


<div class="alert alert-block alert-info">
→ Функцию linspace очень удобно использовать при построении графиков различных функций, поскольку она позволяет получить равномерный массив чисел, к которому можно применить исследуемую функцию и показать результат на графике. Вы научитесь это делать в модуле, посвящённом визуализации.
</div>