# Модуль NumPy. Случайные числа

## `.rand`

In [14]:
import numpy as np
np.random.rand()

0.890583845256933

In [15]:
np.random.rand() * 100

33.831517876522454

In [16]:
np.random.rand(5)

array([0.5781736 , 0.54810415, 0.52543857, 0.21256023, 0.7334865 ])

Можно создать многомерный массив (2 ряда, 3 столбца):

In [17]:
np.random.rand(2, 3)

array([[0.26630137, 0.51559668, 0.43133694],
       [0.6206648 , 0.75615169, 0.40182789]])

In [18]:
np.random.rand(2, 3, 4)

array([[[0.99185533, 0.54397447, 0.94533437, 0.51712758],
        [0.5683586 , 0.77532635, 0.10710601, 0.94519891],
        [0.13588949, 0.08153571, 0.0895291 , 0.17644663]],

       [[0.44860462, 0.52608523, 0.84634972, 0.76690622],
        [0.21951854, 0.90435149, 0.47295872, 0.85747096],
        [0.17825895, 0.30998333, 0.95871697, 0.70816424]]])

In [23]:
shape = (2, 3)
# np.random.rand(shape)
# TypeError: 'tuple' object cannot be interpreted as an integer

TypeError: 'tuple' object cannot be interpreted as an integer

In [20]:
np.random.rand(*shape)

array([[0.14371092, 0.72914773, 0.20632061],
       [0.20505287, 0.51563924, 0.3967025 ]])

## `.sample`

А вот `.sample` принимает кортеж:

In [21]:
np.random.sample(shape)

array([[0.80886702, 0.88722825, 0.9597395 ],
       [0.21521008, 0.07861615, 0.91665833]])

## `.uniform`

In [22]:
np.random.uniform()

0.6176898712577252

Эта функция принимает граничные значения:

In [24]:
np.random.uniform(10, 20)

15.219994058722033

И также может создавать массив:

In [25]:
np.random.uniform(10, 20, size=5)

array([11.03016311, 10.44917013, 14.90412645, 19.92786929, 19.69805366])

In [26]:
np.random.uniform(10, 20, size=(2, 3))

array([[17.31894543, 11.64516486, 16.71987944],
       [12.76028583, 16.32342542, 15.48307019]])

In [27]:
np.random.uniform(10, 20, size=shape)

array([[10.13905757, 13.22993101, 13.44374734],
       [11.20515147, 17.22218687, 16.96728032]])

## `.randint`

From 0 till first arg(not incl):

In [29]:
np.random.randint(10)

8

From ...(incl) till ...(not incl):

In [30]:
np.random.randint(10, 20, size=shape)

array([[15, 13, 12],
       [10, 18, 19]])

## `.shuffle`

Changes the order of the array elements:

In [32]:
arr = np.arange(10)
print(arr)
# [0 1 2 3 4 5 6 7 8 9]
print(np.random.shuffle(arr))
# None
print(arr)
# [2 6 0 9 5 1 4 3 8 7]

[0 1 2 3 4 5 6 7 8 9]
[2 6 0 9 5 1 4 3 8 7]


## `.permutation`

In [35]:
?np.random.permutation

Docstring:
permutation(x)

Randomly permute a sequence, or return a permuted range.

If `x` is a multi-dimensional array, it is only shuffled along its
first index.

.. note::
    New code should use the
    `~numpy.random.Generator.permutation`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
x : int or array_like
    If `x` is an integer, randomly permute ``np.arange(x)``.
    If `x` is an array, make a copy and shuffle the elements
    randomly.

Returns
-------
out : ndarray
    Permuted sequence or array range.

See Also
--------
random.Generator.permutation: which should be used for new code.

Examples
--------
>>> np.random.permutation(10)
array([1, 7, 4, 3, 0, 9, 2, 5, 8, 6]) # random

>>> np.random.permutation([1, 4, 9, 12, 15])
array([15,  1,  9,  4, 12]) # random

>>> arr = np.arange(9).reshape((3, 3))
>>> np.random.permutation(arr)
array([[6, 7, 8], # random
       [0, 1, 2],
       [3, 4, 5]])


In [36]:
playlist = ["The Beatles", "Pink Floyd", "ACDC", "Deep Purple"]

In [37]:
shuffled = np. random. permutation(playlist)
print (shuffled)
# ['The Beatles' 'Pink Floyd' 'Deep Purple' 'ACDC' ]
print (playlist)
# ['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple' ]

['The Beatles' 'Deep Purple' 'Pink Floyd' 'ACDC']
['The Beatles', 'Pink Floyd', 'ACDC', 'Deep Purple']


In [38]:
np.random.permutation(10)

array([3, 6, 5, 7, 4, 1, 9, 2, 0, 8])

## `.choice`

In [39]:
?np.random.choice

Docstring:
choice(a, size=None, replace=True, p=None)

Generates a random sample from a given 1-D array

.. versionadded:: 1.7.0

.. note::
    New code should use the `~numpy.random.Generator.choice`
    method of a `~numpy.random.Generator` instance instead;
    please see the :ref:`random-quick-start`.

Parameters
----------
a : 1-D array-like or int
    If an ndarray, a random sample is generated from its elements.
    If an int, the random sample is generated as if it were ``np.arange(a)``
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  Default is None, in which case a
    single value is returned.
replace : boolean, optional
    Whether the sample is with or without replacement. Default is True,
    meaning that a value of ``a`` can be selected multiple times.
p : 1-D array-like, optional
    The probabilities associated with each entry in a.
    If not given, the sample assumes a unif

In [40]:
np.random.choice(5, size=shape)

array([[3, 4, 2],
       [4, 4, 3]])

In [45]:
workers = ["Alice", "Bob", "Charlie", "David", "Edgar"]
choice = np.random.choice(workers, size=3, replace=False)
choice

array(['David', 'Bob', 'Edgar'], dtype='<U7')

In [47]:
choice = np.random.choice(workers, size=3, replace=True)
choice

array(['David', 'Bob', 'David'], dtype='<U7')

In [52]:
choice = np.random.choice(workers, size=10, replace=True)
choice

array(['Bob', 'Bob', 'Alice', 'Bob', 'Alice', 'Bob', 'Edgar', 'Charlie',
       'Alice', 'Charlie'], dtype='<U7')

In [51]:
# choice = np.random.choice(workers, size=10, replace=False)
# choice
# ValueError: Cannot take a larger sample than population when 'replace=False'

ValueError: Cannot take a larger sample than population when 'replace=False'

## `.seed`

In [56]:
np.random.seed(23)
np.random.randint(10, size=(3,4))
# array([[3, 6, 8, 9],
#        [6, 8, 7, 9],
#        [3, 6, 1, 2]])

array([[3, 6, 8, 9],
       [6, 8, 7, 9],
       [3, 6, 1, 2]])

In [58]:
np. random. seed (100)
print(np.random.randint(10,size=3))
# [8 8 3]
print(np.random.randint(10,size=3))
# [7 7 0]
print(np.random.randint(10,size=3))
# [4 2 5]

[8 8 3]
[7 7 0]
[4 2 5]


Seed maximum:

In [57]:
2**32 - 1

4294967295

In [ ]:
arr = np.arange(10)